version: "3"
services:
  buy_btc:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - USD_BUY
    command:
      - python
      - /app/buy_btc.py
  sell_btc:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - BTC_SELL
    command:
      - python
      - /app/sell_btc.py
  load_candles:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - PG_HOST
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - SLACK_BOT_TOKEN
      - SLACK_CHANNEL
    command:
      - python
      - /app/load_candles.py
