version: '3'
services:
  private:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - REQUEST_SUFFIX=accounts
    command:
      - python
      - /app/private.py
  public:
    build: ./src
    environment:
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - LOOKBACK=200
      - PRODUCT_ID=BTC-USD
      - GRANULARITY=86400
    command:
      - python
      - /app/public.py
  ws:
    build: ./src
    environment:
      - CB_WEBSOCKET_URL=wss://ws-feed-public.sandbox.pro.coinbase.com
      - CHANNEL=ticker
      - PRODUCT_ID=BTC-USD
    command:
      - python
      - /app/ws.py
