version: "3"
services:
  bot:
    build: ./src
    environment:
      - SLACK_BOT_TOKEN
      - SLACK_CHANNEL
      - CB_REST_URL=https://api.pro.coinbase.com
      - PRODUCT_ID=BTC-USD
    command:
      - python
      - /app/bot.py
  private:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - REQUEST_SUFFIX=accounts
      - MAX_REQUESTS=5
    command:
      - python
      - /app/private.py
  public:
    build: ./src
    environment:
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - LOOKBACK=200
      - PRODUCT_ID=BTC-USD
      - GRANULARITY=86400
    command:
      - python
      - /app/public.py
  ws:
    build: ./src
    environment:
      - CB_WEBSOCKET_URL=wss://ws-feed-public.sandbox.pro.coinbase.com
      - CHANNEL=ticker
      - PRODUCT_ID=BTC-USD
    command:
      - python
      - /app/ws.py

  buy_btc:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - USD_BUY
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - MAX_REQUESTS=3
    command:
      - python
      - /app/buy_btc.py

  sell_btc:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - USD_SELL
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - MAX_REQUESTS=5
    command:
      - python
      - /app/sell_btc.py

  load_candles:
    build: ./src
    environment:
      - PG_HOST
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - SLACK_BOT_TOKEN
      - SLACK_CHANNEL
      - CB_REST_URL=https://api.pro.coinbase.com
      - LOOKBACK=5
      - PRODUCT_ID=BTC-USD
      - GRANULARITY=60
    command:
      - python
      - /app/load_candles.py

  main:
    build: ./src
    environment:
      - CB_API_KEY
      - CB_API_SECRET
      - CB_PASSPHRASE
      - PG_HOST
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - SLACK_BOT_TOKEN
      - SLACK_CHANNEL
      - CB_REST_URL=https://api-public.sandbox.pro.coinbase.com
      - LOOKBACK=5
      - PRODUCT_ID=BTC-USD
      - GRANULARITY=60
      - MAX_REQUESTS=5
    command:
      - python
      - /app/main.py
